# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QwHH3H_A0XFucQH_OUJuhbKSt-cuVBuJ
"""

print("Hello World")